services:
  tg-bawer:
    build: .
    container_name: tg-bawer
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
